export const STRINGS_EN = {
  routes: {
    urlHome: 'home',
    urRegisterCarIn: 'register',
    urlRegisterCarOut: 'delivery',
    urlCarPark: 'parking-details',
    urlStatistics: 'statistics-estacionamiento'
  },
  car: {
    exit: 'Exit',
    model: 'Brand',
    entry: 'Entry',
    outDate: 'Departure date',
    entryDate: 'Ingress date',
    licencePlate: 'Licence plate',
  },

  find: 'Find',
  aceppt: 'Accept',
  position: 'Position',
  canceled: 'Cancel',
  isEmpty: 'Empty',
  require: ' reuqired',
  statistics: 'statistics',
  exitCar: 'Deliver automobile',
  totalAccount: 'Total a pagar',
  parkingCar: 'Estacionamiento',
  register: 'Registrar vehículo',
  timeOccupated: 'Tiempo ocupado',
  numberAccess: 'Número de acceso',
  lastPosition: 'Posición inicial',
  mostVisited: 'Puestos mas usados',
  copyright: 'Diseño de José Ortíz',
  generateInvoice: 'Generar factura',
  timeInCourse: 'Tiempo transcurrido',
  actuallyPosition: 'Posición actual',
  parkingName: 'Estacionamiento el Maguary',
  actuallyCar: ' Carros en el estacionamiento',
  parkingCarFull: 'No existen puestos disponibles',
  ingressLicencePlate: 'Ingrese el número de placa',
  registerSuccess: 'Vehículo estacionado correctamente',
  generateInvoiceContent: 'Esta seguro que desea retirar su carro?',
  registerCarConfirm: 'Esta seguro que desea registrar el vehiculo?',
  invoiceGenerateDescription: 'Factura generada del estacionamiento el maguary, perteneciente a Francisco',
  notExistCar: 'Lo lamentamos, el vehiculo solicitado no esta estacionado, intente con otro número de placa',
  parkingSlogan: 'Tu vehículo esta protegido por el Duida Marawaka,' +
    ' nacido en las orillas del cerro Autana, bañado por el agua del padre orinoco'
};
