export const STRINGS_ES = {
    routes: {
        urlHome: 'home',
        urlAdmin: 'Administrar',
        urRegisterCarIn: 'registrar',
        urlRegisterCarOut: 'entregar',
        urlCarPark: 'estacionamiento-detalle',
        urlStatistics: 'estadisiticas-estacionamiento'
    },
    car: {
        exit: 'Salir',
        model: 'Marca',
        entry: 'Entrada',
        outDate: 'Fecha salida',
        entryDate: 'Fecha ingreso',
        licencePlate: 'Número de placa',
    },

    find: 'Buscar',
    aceppt: 'Aceptar',
    position: 'Puesto',
    canceled: 'Cancelar',
    isEmpty: 'Desocupado',
    require: ' es requerido',
    statistics: 'Estadísticas',
    exitCar: 'Entregar vehículo',
    totalAccount: 'Total a pagar',
    parkingCar: 'Estacionamiento',
    register: 'Registrar vehículo',
    timeOccupated: 'Tiempo ocupado',
    numberAccess: 'Número de acceso',
    lastPosition: 'Posición inicial',
    mostVisited: 'Puestos mas usados',
    copyright: 'Diseño de José Ortíz',
    generateInvoice: 'Generar factura',
    timeInCourse: 'Tiempo transcurrido',
    createCarPark: 'Crear Estacionamiento',
    numberPosition: 'Número de Puestos',
    actuallyPosition: 'Posición actual',
    parkingName: 'Estacionamiento el Maguary',
    deleteParkingCar: 'Eliminar estacionamiento',
    minNumber: 'Número minimo de posiciones es igual a 2',
    actuallyCar: ' Vehículos en el estacionamiento',
    parkingCarFull: 'No existen puestos disponibles',
    ingressLicencePlate: 'Ingrese el número de placa',
    exitCarFail: 'A ocurrido un error, intente mas tarde',
    registerSuccess: 'Vehículo estacionado correctamente',
    exitCarSuccessTitle: 'Vehículo entregado satisfactoriamente',
    registerFail: 'El vehículo ya se encuentra en el estacionamiento',
    generateInvoiceContent: 'Esta seguro que desea retirar su vehículo?',
    registerCarConfirm: 'Esta seguro que desea registrar el vehiculo?',
    exitCarSuccess: 'Revise el portal de Alegra para ver el detalle de la factura',
    deleteParkingCarConfirm: 'Esta seguro de eliminar el estacionamiento? recuerde que dicha acción no puede ser devuelta.',
    invoiceGenerateDescription: 'Factura generada el ${0} en el estacionamiento el maguary,' +
        ' perteneciente a francisco, al cliente ${1}, por un monto de ${2}',
    notExistCar: 'Lo lamentamos, el vehiculo solicitado no esta estacionado, intente con otro número de placa',
    parkingSlogan: 'Tu vehículo esta protegido por el Duida Marawaka,' +
        ' nacido en las orillas del cerro Autana, bañado por el agua del padre orinoco'
};
